export const TEST_DISPATCH = "TEST_DISPATCH";
export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOTFOUND = "PROFILE_NOTFOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";

export const POST_LOADING = "POST_LOADING";
export const GET_POSTS = "GET_POSTS";
export const GET_POST = "GET_POST";
export const ADD_POST = "ADD_POST";
export const DELETE_POST = "DELETE_POST";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// Home
export const GET_DATA = "GET_DATA";
export const INITIAL_DEVICE = "INITIAL_DEVICE";
export const TESTING = "TESTING";

// Alrm
export const UPDATE_ALARM = "UPDATE_ALARM";
export const GET_ALARM = "GET_ALARM";

// Control
export const CONTROL_MANUAL = "CONTROL_MANUAL ";
export const GET_CONTROL = "GET_CONTROL";
export const FAN_CONTROL = "FAN_CONTROL";
export const HUM_CONTROL = "HUM_CONTROL";
export const CAR_CONTROL = "CAR_CONTROL";
//Control senrsor1
export const SEN1_FAN1_CONTROL_ON = "SEN1_FAN1_CONTROL_ON";
export const SEN1_FAN1_CONTROL_OFF = "SEN1_FAN1_CONTROL_OFF";
export const SEN1_FAN2_CONTROL_ON = "SEN1_FAN2_CONTROL_ON";
export const SEN1_FAN2_CONTROL_OFF = "SEN1_FAN2_CONTROL_OFF";
export const SEN1_HUM1_CONTROL_ON = "SEN1_HUM1_CONTROL_ON";
export const SEN1_HUM1_CONTROL_OFF = "SEN1_HUM1_CONTROL_OFF";
export const SEN1_HUM2_CONTROL_ON = "SEN1_HUM2_CONTROL_ON";
export const SEN1_HUM2_CONTROL_OFF = "SEN1_HUM2_CONTROL_OFF";
export const SEN1_SHOCKTEM1_CONTROL_ON = "SEN1_SHOCKTEM1_CONTROL_ON";
export const SEN1_SHOCKTEM1_CONTROL_OFF = "SEN1_SHOCKTEM1_CONTROL_OFF";
export const SEN1_SHOCKTEM2_CONTROL_ON = "SEN1_SHOCKTEM2_CONTROL_ON";
export const SEN1_SHOCKTEM2_CONTROL_OFF = "SEN1_SHOCKTEM2_CONTROL_OFF";
export const SEN1_LIGHT1_CONTROL_ON = "SEN1_LIGHT1_CONTROL_ON";
export const SEN1_LIGHT1_CONTROL_OFF = "SEN1_LIGHT1_CONTROL_OFF";
export const SEN1_LIGHT2_CONTROL_ON = "SEN1_LIGHT2_CONTROL_ON";
export const SEN1_LIGHT2_CONTROL_OFF = "SEN1_LIGHT2_CONTROL_OFF";
export const SEN1_ROOF1_CONTROL_ON = "SEN1_ROOF1_CONTROL_ON";
export const SEN1_ROOF1_CONTROL_OFF = "SEN1_ROOF1_CONTROL_OFF";
export const SEN1_ROOF2_CONTROL_ON = "SEN1_ROOF2_CONTROL_ON";
export const SEN1_ROOF2_CONTROL_OFF = "SEN1_ROOF2_CONTROL_OFF";
export const SEN1_FANCO1_CONTROL_ON = "SEN1_FANCO1_CONTROL_ON";
export const SEN1_FANCO1_CONTROL_OFF = "SEN1_FANCO1_CONTROL_OFF";
export const SEN1_FANCO2_CONTROL_ON = "SEN1_FANCO2_CONTROL_ON";
export const SEN1_FANCO2_CONTROL_OFF = "SEN1_FANCO2_CONTROL_OFF";
//Control senrsor2
export const SEN2_FAN1_CONTROL_ON = "SEN2_FAN1_CONTROL_ON";
export const SEN2_FAN1_CONTROL_OFF = "SEN2_FAN1_CONTROL_OFF";
export const SEN2_FAN2_CONTROL_ON = "SEN2_FAN2_CONTROL_ON";
export const SEN2_FAN2_CONTROL_OFF = "SEN2_FAN2_CONTROL_OFF";
export const SEN2_HUM1_CONTROL_ON = "SEN2_HUM1_CONTROL_ON";
export const SEN2_HUM1_CONTROL_OFF = "SEN2_HUM1_CONTROL_OFF";
export const SEN2_HUM2_CONTROL_ON = "SEN2_HUM2_CONTROL_ON";
export const SEN2_HUM2_CONTROL_OFF = "SEN2_HUM2_CONTROL_OFF";
export const SEN2_SHOCKTEM1_CONTROL_ON = "SEN2_SHOCKTEM1_CONTROL_ON";
export const SEN2_SHOCKTEM1_CONTROL_OFF = "SEN2_SHOCKTEM1_CONTROL_OFF";
export const SEN2_SHOCKTEM2_CONTROL_ON = "SEN2_SHOCKTEM2_CONTROL_ON";
export const SEN2_SHOCKTEM2_CONTROL_OFF = "SEN2_SHOCKTEM2_CONTROL_OFF";
export const SEN2_LIGHT1_CONTROL_ON = "SEN2_LIGHT1_CONTROL_ON";
export const SEN2_LIGHT1_CONTROL_OFF = "SEN2_LIGHT1_CONTROL_OFF";
export const SEN2_LIGHT2_CONTROL_ON = "SEN2_LIGHT2_CONTROL_ON";
export const SEN2_LIGHT2_CONTROL_OFF = "SEN2_LIGHT2_CONTROL_OFF";
export const SEN2_ROOF1_CONTROL_ON = "SEN2_ROOF1_CONTROL_ON";
export const SEN2_ROOF1_CONTROL_OFF = "SEN2_ROOF1_CONTROL_OFF";
export const SEN2_ROOF2_CONTROL_ON = "SEN2_ROOF2_CONTROL_ON";
export const SEN2_ROOF2_CONTROL_OFF = "SEN2_ROOF2_CONTROL_OFF";
export const SEN2_FANCO1_CONTROL_ON = "SEN2_FANCO1_CONTROL_ON";
export const SEN2_FANCO1_CONTROL_OFF = "SEN2_FANCO1_CONTROL_OFF";
export const SEN2_FANCO2_CONTROL_ON = "SEN2_FANCO2_CONTROL_ON";
export const SEN2_FANCO2_CONTROL_OFF = "SEN2_FANCO2_CONTROL_OFF";

/// Get data from sensor
export const GET_DATA_SENSOR1 = "GET_DATA_SENSOR1";
export const GET_DATA_SENSOR2 = "GET_DATA_SENSOR2";
export const GET_ALARM_SENSOR1 = "GET_ALARM_SENSOR1";
export const GET_ALARM_SENSOR2 = "GET_ALARM_SENSOR2";

// Update alarm 1
export const UPDATE_ALARM_SENSOR1 = "UPDATE_ALARM_SENSOR1";
export const UPDATE_ALARM_SENSOR2 = "UPDATE_ALARM_SENSOR2";

//
export const TESTING2 = "TESTING2";
